# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [37]:
city_data=pd.read_csv('city_data.csv')
city_data

,Unnamed: 0,City,Latitude,Longitude,Humidity,Wind_Speed,TemperatureK,Cloudiness,Temperature
0,0,Busselton,-33.65,115.33,94,0.89,283.92,2,51
1,1,Ixtapa,20.70,-105.20,74,3.60,303.15,75,85
2,2,Arraial do Cabo,-22.97,-42.03,66,2.60,296.51,5,74
3,3,Rincon,32.30,-81.24,59,1.86,300.87,20,81
4,4,Bluff,-46.60,168.33,75,5.87,282.32,79,48
...,...,...,...,...,...,...,...,...,...
614,614,Gushikawa,26.35,127.87,75,5.10,305.03,40,89
615,615,Oddur,4.12,43.89,81,7.88,294.89,81,71
616,616,Nishihara,26.18,127.76,79,4.10,305.07,40,89
617,617,Khovd,48.01,91.64,42,1.00,289.95,100,62
618,618,Bāglung,28.27,83.59,71,0.54,297.84,77,76

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [5]:
locations = city_data[["Latitude","Longitude"]]

# Fill NaN values and convert to float
rating = city_data["Humidity"].astype(int)


fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating,
                                dissipating=False, max_intensity=100,
                                 point_radius=5,opacity = 0.8)


# Add layer


fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
 #city_data.Temperature<80 & city_data.Temperature>70 & city_data.Wind_Speed<10 & city_data.Cloudiness==0

Best_cities=city_data.loc[(city_data.Temperature<80) & (city_data.Wind_Speed<10) & (city_data.Temperature>70)  & (city_data.Cloudiness==0)]
Best_cities.tail()

,Unnamed: 0,City,Latitude,Longitude,Humidity,Wind_Speed,TemperatureK,Cloudiness,Temperature
558,558,Torbat-e Jām,35.24,60.62,22,5.02,299.69,0,79
565,565,Kiryat Gat,31.61,34.76,70,1.67,295.19,0,71
600,600,Antequera,37.02,-4.56,64,2.60,295.81,0,72
606,606,Iracoubo,5.48,-53.20,83,3.45,298.84,0,78
612,612,São João da Barra,-21.64,-41.05,81,2.84,295.41,0,72

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [10]:
str_test="MHPG+CC Port Hedland, Western Australia"
str_list = str_test.split(',')  # list of words

# first word  v              v last word
str_list[0], str_list[-1]

('MHPG+CC Port Hedland', ' Western Australia')

In [19]:
with open('Hotel_info.json') as json_file:
     response= json.load(json_file)
response
Hotel_Name=response["results"][0]["name"]
Hotel_Adress=response["results"][0]["vicinity"]
Hotel_Location=response["results"][0]['geometry']['location']
Hotel_lat=response["results"][0]['geometry']['location']['lat']
Hotel_lng=response["results"][0]['geometry']['location']['lng']
Contry_code=response["results"][0]["plus_code"]['compound_code']
Contry_code_List = Contry_code.split(',')  # list of words
Country_name=str_list[-1]
Country_name

' Western Australia'

In [23]:
target_radius = 50000
target_type = "Hotel"
target_search = "Hotel"
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
Hotel_Names=[]
Hotel_Adresses=[]
Hotel_Locations=[]
Hotel_Lat=[]
Hotel_Lng=[]
Best_cities_List=Best_cities['City']
City_names=[]
Country=[]

# set up a parameters dictionary
i=0
for City in Best_cities_List:
    response=[]
    target_coordinates=str(Best_cities.iloc[i,2])+","+str(Best_cities.iloc[i,3])
    params = {
        "location": target_coordinates,
        "radius": target_radius,
        "type": target_type,
        "key": g_key,
        "keyword": target_search
        }
    try:
        response = requests.get(base_url, params=params).json()
        Hotel_Name=response["results"][0]["name"]
        Hotel_Adress=response["results"][0]["vicinity"]
        Hotel_Location=response["results"][0]['geometry']['location']
        Hotel_lat=response["results"][0]['geometry']['location']['lat']
        Hotel_lng=response["results"][0]['geometry']['location']['lng']
        Contry_code=response["results"][0]["plus_code"]['compound_code']
        
        Contry_code_List = Contry_code.split(',')  # list of words
        Country_name=Contry_code_List[-1]
        
        
        Country.append(Country_name)
        City_names.append(City)
        Hotel_Adresses.append(Hotel_Adress)
        Hotel_Locations.append(Hotel_Location)
        Hotel_Names.append(Hotel_Name)
        Hotel_Lat.append(Hotel_lat)
        Hotel_Lng.append(Hotel_lng)

        
        print (f'We found The best hotel in {City}')
    except:
        print(f'Could not find any {target_search} in {target_radius} meters of {City}')
    #if i==2: break
    i=i+1
# base url

# run a request using our params dictionary
Country

We found The best hotel in Abnūb
We found The best hotel in Port Hedland
We found The best hotel in Sīrjān
We found The best hotel in Kununurra
We found The best hotel in Umluj
We found The best hotel in Changji
We found The best hotel in Ubari
We found The best hotel in Murgab
We found The best hotel in Bayanday
We found The best hotel in Coyaima
We found The best hotel in Marks
We found The best hotel in San Quintín
Could not find any Hotel in 50000 meters of Kyra
We found The best hotel in Guerrero Negro
We found The best hotel in Santa Isabel Rio Negro
We found The best hotel in Shahrud
We found The best hotel in Tūkrah
We found The best hotel in Grand-Santi
We found The best hotel in Colares
We found The best hotel in Khāsh
Could not find any Hotel in 50000 meters of Kushmurun
We found The best hotel in Mana
We found The best hotel in Assiut
We found The best hotel in Lamu
We found The best hotel in Abu Kamal
We found The best hotel in Katherine
We found The best hotel in Torbat-e Jām
We found The best hotel in Kiryat Gat
We found The best hotel in Antequera
We found The best hotel in Iracoubo
We found The best hotel in São João da Barra

[' Egypt',
 ' Western Australia',
 ' Iran',
 ' Western Australia',
 '27F8+48 Umluj Saudi Arabia',
 ' China',
 ' Libya',
 ' Turkmenistan',
 ' Russia',
 ' Colombia',
 ' Russia',
 ' Mexico',
 ' Mexico',
 ' Brazil',
 ' Iran',
 ' Libya',
 ' French Guiana',
 ' Portugal',
 ' Iran',
 ' French Guiana',
 ' Egypt',
 ' Kenya',
 ' Iraq',
 ' Northern Territory',
 ' Iran',
 ' Israel',
 ' Spain',
 ' French Guiana',
 ' Brazil']

In [38]:
Best_Hotel_data = pd.DataFrame({
                                'Country':Country,
                                
                                'City': City_names,
                               'Name': Hotel_Names,
                               'Latitude': Hotel_Lat,
                               'Longitude': Hotel_Lng,
                                'Adress': Hotel_Adresses,
                                'Hotel_Locations': Hotel_Locations,
                            
                                })
#Test=city_data.loc[city_data['City']==Best_Hotel_data['City']]
#Best_Hotel_data.to_csv('Best_Hotel_Data.csv')
Best_Hotel_data

,Country,City,Name,Latitude,Longitude,Adress,Hotel_Locations
0,Egypt,Abnūb,Florence Hotel Assiut,27.187841,31.193165,"1 Kornish Al Nile (Al Thawra), Asyut Second","{'lat': 27.1878408, 'lng': 31.1931653}"
1,Western Australia,Port Hedland,Hospitality Port Hedland,-20.309140,118.606970,"Webster St, Port Hedland","{'lat': -20.3091402, 'lng': 118.6069696}"
2,Iran,Sīrjān,Tourism Hotel,29.452932,55.672858,Sirjan,"{'lat': 29.4529316, 'lng': 55.67285769999999}"
3,Western Australia,Kununurra,Hotel Kununurra,-15.776260,128.738450,"37 Messmate Way, Kununurra","{'lat': -15.77626, 'lng': 128.73845}"
4,27F8+48 Umluj Saudi Arabia,Umluj,Juman Hotel,25.022764,37.265860,"King Abdullah Rd, Umluj","{'lat': 25.022764, 'lng': 37.26586}"
5,China,Changji,Hilton Urumqi,43.875027,87.611840,"1237 Hongguangshan Rd, Shuimogou District, Ürümqi","{'lat': 43.875027, 'lng': 87.61184}"
6,Libya,Ubari,فندق أوباري,26.596688,12.766078,"Unnamed Road, أوباري،","{'lat': 26.5966876, 'lng': 12.7660784}"
7,Turkmenistan,Murgab,Margush Hotel,37.586144,61.853766,Mary,"{'lat': 37.5861441, 'lng': 61.8537656}"
8,Russia,Bayanday,Eco Centre Talovskoe,52.732434,106.008826,"Irkutsk Oblast, Russia, 666133","{'lat': 52.732434, 'lng': 106.0088262}"
9,Colombia,Coyaima,Hotel San Marcelino de las Rosas,3.717425,-74.900888,"Represa De Prado, Prado","{'lat': 3.7174246, 'lng': -74.9008879}"
10,Russia,Marks,Pioneer Luxe Hotel Bohemia,51.530099,46.031011,"Prospekt Kirova, 15/1, Saratov","{'lat': 51.5300988, 'lng': 46.0310105}"
11,Mexico,San Quintín,Mision Santa Maria,30.400381,-115.911920,"Camino Playa Santa Maria S/N, San Quintin, Ens...","{'lat': 30.4003812, 'lng': -115.9119201}"
12,Mexico,Guerrero Negro,Hotel Los Caracoles,27.967758,-114.028336,"Calzada, De La República s/n, Estado 30, Guerr...","{'lat': 27.9677576, 'lng': -114.0283356}"
13,Brazil,Santa Isabel Rio Negro,Hotel Ayuana,-0.416050,-65.019870,Santa Isabel do Rio Negro,"{'lat': -0.4160499, 'lng': -65.0198703}"
14,Iran,Shahrud,Shahab Hotel,36.774157,54.466818,"Gorgan, بلوار نهار خوران 300 متر مانده به کلانتری","{'lat': 36.7741572, 'lng': 54.466818}"
15,Libya,Tūkrah,فندق المرج السياحي,32.495789,20.836220,Al Marj,"{'lat': 32.4957894, 'lng': 20.8362204}"
16,French Guiana,Grand-Santi,Hotel La Villa Couacou,4.250734,-54.382250,Grand-Santi,"{'lat': 4.2507342, 'lng': -54.38225}"
17,Portugal,Colares,Hotel Albatroz Cascais,38.699856,-9.417411,"R. Frederico Arouca 100, Cascais","{'lat': 38.6998556, 'lng': -9.417411099999999}"
18,Iran,Khāsh,خوابگاه دانشجویی خاش,28.209681,61.198720,Khash,"{'lat': 28.2096812, 'lng': 61.1987202}"
19,French Guiana,Mana,Hôtel Amazonia du Fleuve,5.499258,-54.030189,"20 Rue Thiers, Saint-Laurent-du-Maroni","{'lat': 5.4992581, 'lng': -54.0301888}"
20,Egypt,Assiut,Florence Hotel Assiut,27.187841,31.193165,"1 Kornish Al Nile (Al Thawra), Asyut Second","{'lat': 27.1878408, 'lng': 31.1931653}"
21,Kenya,Lamu,Manda Bay Lodge,-2.223351,40.967489,Kenya,"{'lat': -2.223351, 'lng': 40.967489}"
22,Iraq,Abu Kamal,Phosphate hotel,34.432664,41.229029,Al Obaidy,"{'lat': 34.4326644, 'lng': 41.2290287}"
23,Northern Territory,Katherine,Knotts Crossing Resort,-14.445862,132.269177,"Corner of Giles Street & Cameron Street, Kathe...","{'lat': -14.445862, 'lng': 132.2691774}"
24,Iran,Torbat-e Jām,Pardisan Hotel 🏩,35.241279,60.617123,"Torbat-e-Jam, 97","{'lat': 35.2412795, 'lng': 60.6171231}"
25,Israel,Kiryat Gat,Waldorf Astoria Jerusalem,31.777403,35.222048,"Gershon Agron St 26-28, Jerusalem","{'lat': 31.7774033, 'lng': 35.2220485}"
26,Spain,Antequera,AC Hotel by Marriott Malaga Palacio,36.719165,-4.419458,"Calle Cortina del Muelle, 1, Málaga","{'lat': 36.7191649, 'lng': -4.4194584}"
27,French Guiana,Iracoubo,L'oiseau de Paradis,5.362393,-52.962463,RN1 -PK111 Degrad Fontine 97315 Sinnamary,"{'lat': 5.3623934, 'lng': -52.9624634}"
28,Brazil,São João da Barra,Ramada by Wyndham Campos dos Goytacazes Hotel ...,-21.754277,-41.339101,"R. Bruno de Azevedo, 60 - Parque Tamandaré, Ca...","{'lat': -21.754277, 'lng': -41.3391007}"

In [42]:
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.

Best_Hotel_data=pd.read_csv('Best_Hotel_Data.csv')
Best_Hotel_data

city_data.loc[city_data['City'] == Best_Hotel_data['City']]

ValueError: Can only compare identically-labeled Series objects

In [28]:
marker_locations = Best_Hotel_data[['Latitude', 'Longitude']]
Names_List=Best_Hotel_data['Name']
# Create a marker_layer using the poverty list to fill the info box
Best_Hotel_data['Adress']
                          
fig = gmaps.figure()
markers = gmaps.marker_layer(marker_locations,
    info_box_content=[f"Hotel Name: {Names_List[i]} \\n Adress: {Best_Hotel_data['Adress'][i]} " for i in range(len(Names_List))])
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))

In [30]:
# NOTE: Do not change any of the code in this cell
Names_List=Best_Hotel_data['Name']
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in Best_Hotel_data.iterrows()]
locations = Best_Hotel_data[['Latitude', 'Longitude']]

fig = gmaps.figure()
markers = gmaps.marker_layer(locations,info_box_template,
    info_box_content=hotel_info)
fig.add_layer(markers)

Best_cities_Humidity

ating = city_data["Humidity"].astype(int)


# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating,
                                dissipating=False, max_intensity=100,
                                 point_radius=5,opacity = 0.8)

fig.add_layer(heat_layer)

# Display figure
fig

ValueError: weights must be of the same length as locations or None

In [ ]:
# Add marker layer ontop of heat map


# Display figure