# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
city_data=pd.read_csv('city_data.csv')
city_data

,Unnamed: 0,City,Latitude,Longitude,Humidity,Wind_Speed,TemperatureK,Cloudiness,Temperature
0,0,Busselton,-33.65,115.33,94,0.89,283.92,2,51
1,1,Ixtapa,20.70,-105.20,74,3.60,303.15,75,85
2,2,Arraial do Cabo,-22.97,-42.03,66,2.60,296.51,5,74
3,3,Rincon,32.30,-81.24,59,1.86,300.87,20,81
4,4,Bluff,-46.60,168.33,75,5.87,282.32,79,48
...,...,...,...,...,...,...,...,...,...
614,614,Gushikawa,26.35,127.87,75,5.10,305.03,40,89
615,615,Oddur,4.12,43.89,81,7.88,294.89,81,71
616,616,Nishihara,26.18,127.76,79,4.10,305.07,40,89
617,617,Khovd,48.01,91.64,42,1.00,289.95,100,62
618,618,Bāglung,28.27,83.59,71,0.54,297.84,77,76

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [18]:
locations = city_data[["Latitude","Longitude"]]

# Fill NaN values and convert to float
rating = city_data["Humidity"].astype(int)


fig = gmaps.figure(center=(0,0),zoom_level=1.5)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating,
                                dissipating=False, max_intensity=100,
                                 point_radius=2,opacity =.8)


# Add layer


fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [19]:
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.

#city_data.Temperature<80 & city_data.Temperature>70 & city_data.Wind_Speed<10 & city_data.Cloudiness==0

Best_cities=city_data.loc[(city_data.Temperature<80) & (city_data.Wind_Speed<10) & (city_data.Temperature>70)  & (city_data.Cloudiness==0)]
Best_cities.head()

,Unnamed: 0,City,Latitude,Longitude,Humidity,Wind_Speed,TemperatureK,Cloudiness,Temperature
49,49,Abnūb,27.27,31.15,47,4.10,298.15,0,76
50,50,Port Hedland,-20.32,118.57,16,6.20,298.15,0,76
58,58,Sīrjān,29.45,55.68,41,4.12,295.34,0,71
118,118,Kununurra,-15.77,128.73,20,6.70,295.15,0,71
119,119,Umluj,25.02,37.27,73,1.22,299.71,0,79

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [24]:
# You can ignor this part the data frame was alreacy saved as "Best_Hotel_Data.csv"

target_radius = 5000
target_type = "Hotel"
target_search = "Hotel"
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# set up a parameters dictionary

Hotel_Names=[]
Hotel_Adresses=[]
Hotel_Locations=[]
Hotel_Lat=[]
Hotel_Lng=[]
Best_cities_List=Best_cities['City']
City_names=[]
Country=[]
City_Humidity=[]


# run a request using our params dictionary

i=0
for City in Best_cities_List:
    response=[]
    target_coordinates=str(Best_cities.iloc[i,2])+","+str(Best_cities.iloc[i,3])
    params = {
        "location": target_coordinates,
        "radius": target_radius,
        "type": target_type,
        "key": g_key,
        "keyword": target_search
        }
    try:
        response = requests.get(base_url, params=params).json()
        Hotel_Name=response["results"][0]["name"]
        Hotel_Adress=response["results"][0]["vicinity"]
        Hotel_Location=response["results"][0]['geometry']['location']
        Hotel_lat=response["results"][0]['geometry']['location']['lat']
        Hotel_lng=response["results"][0]['geometry']['location']['lng']
        Contry_code=response["results"][0]["plus_code"]['compound_code']
        
        Contry_code_List = Contry_code.split(',')  # list of words
        Country_name=Contry_code_List[-1]
        
        City_Humidity.append(Best_cities.iloc[i,4])
        Country.append(Country_name)
        City_names.append(City)
        Hotel_Adresses.append(Hotel_Adress)
        Hotel_Locations.append(Hotel_Location)
        Hotel_Names.append(Hotel_Name)
        Hotel_Lat.append(Hotel_lat)
        Hotel_Lng.append(Hotel_lng)

        
        print (f'We found a hotel in {City}')
    except:
        print(f'Could not find any {target_search} in {target_radius} meters of {City}')
    #if i==2: break  #For Testing
    i=i+1
# base url

Could not find any Hotel in 5000 meters of Abnūb
We found a hotel in Port Hedland
We found a hotel in Sīrjān
We found a hotel in Kununurra
We found a hotel in Umluj
We found a hotel in Changji
We found a hotel in Ubari
Could not find any Hotel in 5000 meters of Murgab
Could not find any Hotel in 5000 meters of Bayanday
We found a hotel in Coyaima
We found a hotel in Marks
We found a hotel in San Quintín
Could not find any Hotel in 5000 meters of Kyra
We found a hotel in Guerrero Negro
We found a hotel in Santa Isabel Rio Negro
We found a hotel in Shahrud
We found a hotel in Tūkrah
We found a hotel in Grand-Santi
We found a hotel in Colares
We found a hotel in Khāsh
Could not find any Hotel in 5000 meters of Kushmurun
We found a hotel in Mana
We found a hotel in Assiut
We found a hotel in Lamu
Could not find any Hotel in 5000 meters of Abu Kamal
We found a hotel in Katherine
We found a hotel in Torbat-e Jām
We found a hotel in Kiryat Gat
We found a hotel in Antequera
Could not find any Hotel in 5000 meters of Iracoubo
We found a hotel in São João da Barra

In [31]:
# You can ignor this part the  Best_Hotel data frame was alreacy saved as "Best_Hotel_Data.csv"

Best_Hotel_data = pd.DataFrame({
                                'Country':Country,
                                'Humidity':City_Humidity,
                                'City': City_names,
                               'Name': Hotel_Names,
                               'Latitude': Hotel_Lat,
                               'Longitude': Hotel_Lng,
                                'Adress': Hotel_Adresses,
                            
                                })
Best_Hotel_data.to_csv('Best_Hotel_Data.csv')
Best_Hotel_data

,Country,Humidity,City,Name,Latitude,Longitude,Adress
0,Western Australia,16,Port Hedland,ibis Styles Port Hedland,-20.308700,118.610356,"Cnr Lukis And, McGregor St, Port Hedland"
1,Iran,41,Sīrjān,Tourism Hotel,29.452932,55.672858,Sirjan
2,Western Australia,20,Kununurra,Hotel Kununurra,-15.776260,128.738450,"37 Messmate Way, Kununurra"
3,27F8+48 Umluj Saudi Arabia,73,Umluj,Juman Hotel,25.022764,37.265860,"King Abdullah Rd, Umluj"
4,China,31,Changji,7Days Inn Changji Oriental Plaza,44.019288,87.308663,"275 Yan'an N Rd, Changji, Changji Hui Autonomo..."
5,Libya,30,Ubari,فندق أوباري,26.596688,12.766078,"Unnamed Road, أوباري،"
6,Colombia,61,Coyaima,Hotel Central,3.798498,-75.194484,Cra. 4A #3-2 a 3-92
7,Russia,42,Marks,"Cafe Hotel ""Ruslan""",51.695336,46.735580,"кольцо, Marks"
8,Mexico,70,San Quintín,Old Mill Hotel,30.485077,-115.977232,Ensenada
9,Mexico,63,Guerrero Negro,Hotel Los Caracoles,27.967758,-114.028336,"Calzada, De La República s/n, Estado 30, Guerr..."
10,Brazil,80,Santa Isabel Rio Negro,Hotel Ayuana,-0.416050,-65.019870,Santa Isabel do Rio Negro
11,Iran,35,Shahrud,Paramida hotel,36.383545,54.933631,"Shahroud, بلوار دانشگاه هتل پارامیدا، خیابان ت..."
12,Libya,83,Tūkrah,قاعدة فيقا فيقا,32.533817,20.593710,توكرة،
13,French Guiana,90,Grand-Santi,Hotel La Villa Couacou,4.250734,-54.382250,Grand-Santi
14,Portugal,64,Colares,Penha Longa Resort,38.761299,-9.396803,"Estrada da Lagoa Azul Linhó, Lisboa"
15,Iran,64,Khāsh,خوابگاه دانشجویی خاش,28.209681,61.198720,Khash
16,French Guiana,84,Mana,LE SAMANA,5.659991,-53.777033,"18 rue Bruno Aubert, Mana"
17,Egypt,47,Assiut,Florence Hotel Assiut,27.187841,31.193165,"1 Kornish Al Nile (Al Thawra), Asyut Second"
18,Kenya,82,Lamu,The majlis lamu hotel,-2.298980,40.920376,"Lamu West, Lamu"
19,Northern Territory,11,Katherine,ibis Styles Katherine,-14.471673,132.290457,"9 Cyprus St, Katherine"
20,Iran,22,Torbat-e Jām,Pardisan Hotel 🏩,35.241279,60.617123,"Torbat-e-Jam, 97"
21,Israel,70,Kiryat Gat,Desert Gat,31.603043,34.763726,"Sderot HaAtsma'ut 134, Kiryat Gat"
22,Spain,64,Antequera,Hotel Antequera,37.020477,-4.574083,"Av. Alcalde José María González, Antequera"
23,Brazil,81,São João da Barra,Pousada Kactus,-21.665366,-41.023183,"R. Q - Chapéu do Sol, São João da Barra"

In [32]:
# Readig the Best hotel information from CSV File 

Best_Hotel_data=pd.read_csv('Best_Hotel_Data.csv')
Best_Hotel_data
# Best_Hotel_City_List=Best_Hotel_data['City']
# Best_Hotel_Countries=city_data.loc[city_data['City'].isin(Best_Hotel_City_List),city_data['']]

,Unnamed: 0,Country,Humidity,City,Name,Latitude,Longitude,Adress
0,0,Western Australia,16,Port Hedland,ibis Styles Port Hedland,-20.308700,118.610356,"Cnr Lukis And, McGregor St, Port Hedland"
1,1,Iran,41,Sīrjān,Tourism Hotel,29.452932,55.672858,Sirjan
2,2,Western Australia,20,Kununurra,Hotel Kununurra,-15.776260,128.738450,"37 Messmate Way, Kununurra"
3,3,27F8+48 Umluj Saudi Arabia,73,Umluj,Juman Hotel,25.022764,37.265860,"King Abdullah Rd, Umluj"
4,4,China,31,Changji,7Days Inn Changji Oriental Plaza,44.019288,87.308663,"275 Yan'an N Rd, Changji, Changji Hui Autonomo..."
5,5,Libya,30,Ubari,فندق أوباري,26.596688,12.766078,"Unnamed Road, أوباري،"
6,6,Colombia,61,Coyaima,Hotel Central,3.798498,-75.194484,Cra. 4A #3-2 a 3-92
7,7,Russia,42,Marks,"Cafe Hotel ""Ruslan""",51.695336,46.735580,"кольцо, Marks"
8,8,Mexico,70,San Quintín,Old Mill Hotel,30.485077,-115.977232,Ensenada
9,9,Mexico,63,Guerrero Negro,Hotel Los Caracoles,27.967758,-114.028336,"Calzada, De La República s/n, Estado 30, Guerr..."
10,10,Brazil,80,Santa Isabel Rio Negro,Hotel Ayuana,-0.416050,-65.019870,Santa Isabel do Rio Negro
11,11,Iran,35,Shahrud,Paramida hotel,36.383545,54.933631,"Shahroud, بلوار دانشگاه هتل پارامیدا، خیابان ت..."
12,12,Libya,83,Tūkrah,قاعدة فيقا فيقا,32.533817,20.593710,توكرة،
13,13,French Guiana,90,Grand-Santi,Hotel La Villa Couacou,4.250734,-54.382250,Grand-Santi
14,14,Portugal,64,Colares,Penha Longa Resort,38.761299,-9.396803,"Estrada da Lagoa Azul Linhó, Lisboa"
15,15,Iran,64,Khāsh,خوابگاه دانشجویی خاش,28.209681,61.198720,Khash
16,16,French Guiana,84,Mana,LE SAMANA,5.659991,-53.777033,"18 rue Bruno Aubert, Mana"
17,17,Egypt,47,Assiut,Florence Hotel Assiut,27.187841,31.193165,"1 Kornish Al Nile (Al Thawra), Asyut Second"
18,18,Kenya,82,Lamu,The majlis lamu hotel,-2.298980,40.920376,"Lamu West, Lamu"
19,19,Northern Territory,11,Katherine,ibis Styles Katherine,-14.471673,132.290457,"9 Cyprus St, Katherine"
20,20,Iran,22,Torbat-e Jām,Pardisan Hotel 🏩,35.241279,60.617123,"Torbat-e-Jam, 97"
21,21,Israel,70,Kiryat Gat,Desert Gat,31.603043,34.763726,"Sderot HaAtsma'ut 134, Kiryat Gat"
22,22,Spain,64,Antequera,Hotel Antequera,37.020477,-4.574083,"Av. Alcalde José María González, Antequera"
23,23,Brazil,81,São João da Barra,Pousada Kactus,-21.665366,-41.023183,"R. Q - Chapéu do Sol, São João da Barra"

In [33]:
# NOTE: Do not change any of the code in this cell
Names_List=Best_Hotel_data['Name']
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Adress</dt><dd>{Adress}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in Best_Hotel_data.iterrows()]


#Best_Hotels Locations
locations = Best_Hotel_data[['Latitude', 'Longitude']]


#Create Best Hotels Markers Map
fig = gmaps.figure(center=(0,0),zoom_level=2)
markers = gmaps.marker_layer(locations,info_box_template,
    info_box_content=hotel_info)
fig.add_layer(markers)


#Best_cities_Humidity
rating = Best_Hotel_data["Humidity"].astype(int)

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=rating,
                                dissipating=False, max_intensity=100,
                                 point_radius=5,opacity = 0.8)

fig.add_layer(heat_layer)
# Display figure
fig

Figure(layout=FigureLayout(height='420px'))